apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: wil42
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aucaland/InceptionOfThings.git
    targetRevision: HEAD
    path: p3/confs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  automated:
    selfHeal: true
    prune: true