apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-deployment
spec:
  selector:
    matchLabels:
      app: wil42
  replicas: 1
  template:
    metadata:
      labels:
        app: wil42
    spec:
      container:
      - name: wil42
      image: wil42/playground:v1
      ports:
      - containerPort: 8888